### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by andreyskv** [M1Sh0u/pStrength#1]
Hi!

Good job! This is a very nice little library. However, GPL is very restrictive if code is used inside commercial js code. MIT license would be much better if the intention is "feel free to use it". Could you change it? Thank you.

**Comment by graeme-hill** [comment]
+1

**Comment by M1Sh0u** [comment]
Thanks @andreyskv . I've updated the license to MIT.

**Comment by graeme-hill** [comment]
Awesome

**Comment by joonhur** [comment]
Cool
